# Demo 1: Försiktig Python-introduktion

Google colab bygger på så kallade notebooks. I en sådan kan man blanda textavsnitt och Pythonkod. Det gör att det går att skriva rapporten direkt i anslutning till koden (om man vill).

Texten skriv i *Markdown* som är ett sätt att märka upp till exempel rubriker, punktlistor, formler osv som sedan görs om till formaterad text automatiskt.

$y = x^2$

Eftersom google colab är en web-baserad implementation av Python medan våra data är en textfil behöver vi ladda upp data på något sätt. Antingen kan vi koppla colab till en katalog i google drive eller så laddar vi upp filen direkt.

*kursiv text*

**fet text**


In [1]:
#Använd dessa rader för att ladda in filer till mappen /content/ för körning av google colab
from google.colab import files

uploaded_files = files.upload()

ModuleNotFoundError: No module named 'google'

## Python basics
Vi kan ansätta värden på variabler, använda matematik och funktioner på ungefär samma sätt som i Matlab.

För att använda funktioner så behöver vi först importera de bibliotek där de definieras.

In [2]:
import pandas as pd           #Hanterar tabeller
import plotly.express as px   #Hanterar plots
import numpy as np            #Hanterar arrays
import statsmodels.api as sm  #Hanterar statistiska funktioner som linjär regression

ModuleNotFoundError: No module named 'plotly'

Matematik fungerar precis som förväntat. Notera att inget resultat skrivs ut från den här cellen.

In [15]:
x = 1
y = 2
z = x + y

In [4]:
z

3

In [5]:
v1 = np.zeros(z)
v1[0] = 0.33
v1[2] = 42
print(v1)
print(np.shape(v1))

[ 0.33  0.   42.  ]
(3,)


In [6]:
v2 = np.array([1,2,3,44])
print(v2)
print(np.shape(v2))

[ 1  2  3 44]
(4,)


In [7]:
m1 = np.array([[1,2,3],[4,5,6]])
print(m1)
print(np.shape(m1))

[[1 2 3]
 [4 5 6]]
(2, 3)


## Hantera data mha Pandas

In [16]:
# Läs in en fil med .csv data i en tabell
df = pd.read_csv('demo1.csv')

# Namnge kolumnen i tabellen med valfritt namn
df.columns = ['data']

# Visa tabellen
df.head()

data
0   9.6
1  16.1
2  24.9
3  20.4
4  12.7

In [9]:
# Beräkna medel ch median och skriv ut resultatet
print(df['data'].mean())
print(df['data'].median())

21.18095238095238
21.2


In [11]:
# Eller i två steg, genom att spara resultatet som en variabel
mean = df['data'].mean()
median = df['data'].median();
print(mean)
print(median)

21.18095238095238
21.2


Notera att vi skulle kunna skriva ut en av dem (tex medelvärdet) utan att använda print, genom att bara skriva `mean` på sista raden i cellen. Med `print()` får vi större kontroll över utskriften.

In [12]:
df.describe()

data
count  21.000000
mean   21.180952
std     9.001812
min     8.900000
25%    14.000000
50%    21.200000
75%    25.800000
max    45.000000

In [ ]:
# Ibland är det lättare att läsa tabellen om vi byter plats på axlarna
df.describe().transpose()

count       mean       std  min   25%   50%   75%   max
data   21.0  21.180952  9.001812  8.9  14.0  21.2  25.8  45.0

In [ ]:
# Snabbkommando för att visa en rad statistiska värden för tabellen
display(df.describe().transpose())

#Standard för percentilerna är 25%, 50%, ch 75%. Sätt egna percentiler såhär:
percs = [.20, .50, .80]
display(df.describe(percentiles=percs).transpose())

count       mean       std  min   25%   50%   75%   max
data   21.0  21.180952  9.001812  8.9  14.0  21.2  25.8  45.0

count       mean       std  min   20%   50%   80%   max
data   21.0  21.180952  9.001812  8.9  12.7  21.2  27.1  45.0

In [ ]:
# Om tabellen hade innehållit flera kolumner och vi bara vill ha statstik på en av dessa, kan man t ex gröpa ut datat i denna kolumnen,
# göra denna till en dataframe och sedan ta describe på detta.
display(df['data'].to_frame().describe())

data
count  21.000000
mean   21.180952
std     9.001812
min     8.900000
25%    14.000000
50%    21.200000
75%    25.800000
max    45.000000

## Plocka ut delar av data

In [17]:
# Sätter "True" eller "False" för varje rad som uppfyller villkoret, här att vara mindre än 45. Detta sparas i nya tabellen radindex_under_45
radindex_under_45 = df['data'] < 45
radindex_under_45.head(5)

0    True
1    True
2    True
3    True
4    True
Name: data, dtype: bool

In [ ]:
# Plockar ut raderna med "True" och lägger in dem i en ny tabell
df_below_45 = df[radindex_under_45]

# Visa nya tabellen som nu exkluderar värdet 45 (rad 13)
display(df_below_45)

data
0    9.6
1   16.1
2   24.9
3   20.4
4   12.7
5   21.2
6   30.2
7   25.8
8   18.5
9   10.3
10  25.3
11  14.0
12  27.1
14  23.3
15  24.2
16  14.6
17   8.9
18  32.4
19  11.8
20  28.5

## Visualisera

In [18]:
# Visa en boxplot.
# Data vi använder här tas från tabellen df. "data" motsvarar tabellens kolumnnamn som vi vill använda.
fig = px.box(df, y="data") #df kan t.ex. bytas ut mot df_below_45 som då i stället visar en boxplot på tabellen som exluderar värdet 45

# En figure kan uppdateras och anpassas på olika vis genom fig.update_layout

# Möjliga teman på plottens utseende kan väljas från någon av
# "plotly", "plotly_white", "plotly_dark", "ggplot2", "seaborn", "simple_white", "none"
fig.update_layout(template="plotly_white", title="Box plot")
fig.show()

In [ ]:
#Violin plot är en liknande variant
fig = px.violin(df, y="data", box=True, template="ggplot2", title="Violin plot") #Övriga inställningar kan också läggas in direkt, som här
fig.show()

In [ ]:
fig = px.histogram(df, x="data", nbins=5, title="Histogram") #Plotly korrigerar ibland +/- 1 bins utefter vad den själv tycker blir bäst
fig.show()

## Scatterplot och regression



In [28]:
# Skapa lite nya data

mu, sigma = 0, 0.1 # mean and standard deviation

# Skapa en array med 20 värden från 0 upp till 10 (9.5 blir då sista värdet),
# med intervallet 0.5
xval = np.arange(0, 10, 0.5)
yval = 1 + 0.35 * xval + np.random.normal(mu, sigma, len(xval))
#y-värdena blir en funktion av x värdena med random gaussian noise (normalfördelat brus)

#Lägg in x-värden och y-värden i varsin kolumn i en tabell
df2 = pd.DataFrame({"xval": xval, "yval": yval})

# Plotta med t ex plotly express
fig = px.scatter(df2, x='xval', y='yval', title="Scatter plot", trendline="ols")

# trendline lägger till least squares linjen

fig.show()

In [31]:
# lägger till en konstant för att skatta intercept
df2['const'] = 1

# väljer variabler för regressionen
Y = df2['yval']
X = df2[['const', 'xval']]

model = sm.OLS(Y, X).fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                   yval   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                     1686.
Date:                Mon, 30 Oct 2023   Prob (F-statistic):           3.05e-19
Time:                        22:38:33   Log-Likelihood:                 16.930
No. Observations:                  20   AIC:                            -29.86
Df Residuals:                      18   BIC:                            -27.87
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9810      0.047     20.809      0.0